= Code lounge Kubernetes

Two part tutorial, GKE and bare metal node running on Vagrant.

=== Local setup.

We need to attempt to speed up the download and so we want to point our Docker downloads at a local cache, along as allowing us to
push them to a local repository. 

Please modify your Docker Daemon - if you are running on Linux, edit /etc/default/docker. 

If running on MacOS 10 (X) please edit /var/lib/boot2docker/profile - edit the EXTRA_ARGS

----
EXTRA_ARGS='--label provider=vmwarefusion --insecure-registry=192.168.1.134:5001 --registry-mirror=http://192.168.1.134:5000'
----

Just add the --insecure-registry and --registry-mirror

Typically you can restart with:

----
sudo /etc/init.d/docker restart
----

If you are on systemd you are on your own.

=== Setting up your Kubernetes Cluster

==== GKE setup

INFORMATION: Come in from Slides (Time to start your kubernetes cluster)

You need to ensure that you have the Google Cloud Tools API installed and gcloud init run. We will set up a new project for this
walk through.

1. go to https://console.cloud.google.com[Cloud Console]. On the top right corner, choose the Projects dropdown and choose Create a Project.
2. call the project "codelounge" - it will always give you a project-id that is different from your "name". We will use "codelounge-1304"
3. go to your command line tools and type in

----
gcloud components install kubectl
# when it has finished
kubectl config view
----


It should tell you have no cluster details. So lets create some.

----
gcloud container clusters create codelounge \
  --disk-size 200 \
  --enable-cloud-logging \
  --enable-cloud-monitoring \
  --machine-type n1-standard-1 \
  --num-nodes 3
----

==== Enabling GKE on your project

WARNING: if you get an error similar to:

----
ERROR: (gcloud.container.clusters.create) The required property [zone] is not currently set.
It can be set on a per-command basis by re-running your command with the [--zone] flag.

You may set it for your current workspace by running:

  $ gcloud config set compute/zone VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_COMPUTE_ZONE]
----

type in

----
gcloud compute zones list
----

Use the URL suggested to visit the URL to turn on the resource. It can take a little while.

----
gcloud config set compute/zone us-east1-b
----

WARNING: if you get an error like:

go the https://console.cloud.google.com/iam-admin/serviceaccounts/project?project=codelounge-1304[Service Accounts]
(your url may be slightly different), add a key, and download it. and type

 ----
 gcloud auth activate-service-account --key-file key-file-name.json
 ----

 Try creating the container nodes again and it may ask you to enable another api.

You should now be able to run your gcloud command to create your cluster. If you type the command in again, it may
take a little while before it succeeds as it does take a little while to provision.


==== Check your kubernetes config

----
kubectl config view
kubectl get nodes
kubectl get pods (should show nothing)
----

You can go into the https://console.cloud.google.com[Google Cloud console] and see your nodes, and even ssh into them (click button on right of list)

INFORMATION: Back to slides

==== Deploy a new pod (nginx)

INFORMATION: Slides entry point (Kubernetes Concepts - templates and pods)

----
kubectl run -i --tty busybox --image=busybox
----

It will bring the pod up and ask for you  to "hit enter". I had to use ctrl-j for this.

in another window, get the list of pods, you should see a pod named busybox + a number, this identifies it as this specific busybox.

if you type

----
kubectl get pods
kubectl edit pod busybox-3008257414-io7m5
kubectl describe pod busybox-3008257414-io7m5
kubectl get -o yaml pod busybox-3008257414-io7m5
----

where busybox-3008257414 is the name of the pod, you will see the manifest that Kubernetes created for that pod.

Now try and kill the pod

----
kubectl get pods
kubectl delete pod busybox-3008257414-io7m5
kubectl get pods
----

What happens?

INFORMATION: Back to the Slides

=== Looking at what else you have

----
kubectl get
----

Shows you a lot of different types.

----
kubectl get rs
kubectl get deployments
----

WARNING: if vi plays up for you, you may have to enter *export KUBE_EDITOR=nano*

Edit the busybox deployment and set the number of replicas to 0. Save the file and then watch the pods.

Leave the deployment in place, you will need it again soon.

=== Deploying a service

We now want to create a basic nginx pod that will expose its services on port 80 and create a service.
We can do this in one step using:

kubectl run nginx --image=nginx --port=80 --expose

This allows us to:

----
kubectl get services
----

There is no external ip, we can fix this by editing the service and setting its type to load balancer:

----
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-05-07T07:41:57Z
  name: nginx
  namespace: default
  resourceVersion: "433"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 2d0f0be1-1427-11e6-9d73-42010af0002e
spec:
  clusterIP: 10.3.249.76
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
----

if you now do (after a short while):

----
kubectl get services
----

You will see an external ip, put it in your browser. Get others in the group to hit it.

----
kubectl logs nginx-1830148962-334pi
----

==== Lets change the web page

figure out where it goes:

----
kubectl exec nginx-2176846515-e65ah -c nginx -it -- bash
----

go look in /etc/nginx/conf.d

then edit the deployment

----
kubectl edit deployment nginx
----

update the volumeMounts and volume section as follows:

----
template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - gitRepo:
          repository: https://github.com/rvowles/kubernetes-codelounge.git
          revision: 5fa0ff1e010c5473a5aeaf9de7eae2c438620296
        name: nginx-html
----

it doesn't work, how do you figure out why?

==== ConfigMaps to the rescue

ConfigMaps allow you to store name value pairs of name = string, file or json blob. In our case, we want to be able
to change the configuration of nginx and we can do this by creating a folder called conf.d and putting the new default.conf
in it. Thanks to Viktor, Anthony, Mike and Carl for helping get through this.

----
mkdir conf.d
cat - >conf.d/default.conf
----

paste the next section, then ctrl-d

----
server {
    listen       80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
        root   /usr/share/nginx/html/kubernetes-codelounge;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .h root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
----

now make the

----
kubectl create configmap nginx-config --from-file=conf.d
----

check it is there

----
kubectl get configmap nginx-config -o yaml
----

ok - ready to put it into our deployment:

----
kubectl edit deployment nginx
----

make the volumes and volumeMounts section look like this:

----
template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - gitRepo:
          repository: https://github.com/rvowles/kubernetes-codelounge.git
          revision: 5fa0ff1e010c5473a5aeaf9de7eae2c438620296
        name: nginx-html
      - configMap:
          name: nginx-config
        name: nginx-config
----

save it and deploy again, and if you hit the site, all is joy again.

==== That Node Hello World Example

Ideally we would like our nodejs hello world example being served, and we can do this but creating the docker image,
pushing it into the Google repository and then creating our Deployment and Service.

